apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-go-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-go-api
  template:
    metadata:
      labels:
        app: secure-go-api
    spec:
      containers:
        - name: secure-go-api
          image: ghcr.io/jed212/secure-ci-pipeline/secure-go-api@sha256:e2a377f51d57f8b3ac015349f57487779a4f5d97dbcfe787c00dd5b868e5e08e
          ports:
            - containerPort: 8080
